### PR TITLE
Bumped Helm version from v3.3.0 to v3.7.1

### PR DESCRIPTION
**Pull request by pietervdheijden-calvi**
Updated Helm to the latest version: v3.7.1.

A lot of breaking changes were introduced in Helm v3.7.0:

> A few major changes were made to the experimental OCI feature:
> 
> * helm chart export has been removed
> * helm chart list has been removed
> * helm chart pull has been replaced with helm pull
> * helm chart push has been replaced with helm push
> * helm chart remove has been removed
> * helm chart save has been replaced with helm package

Source: https://github.com/helm/helm/releases

Therefore, I'd recommend to update the major version of Docker image `octopusdeploy/worker-tools`. For example: `4.0.0`.

I've created my own Docker image (see: [pvanderheijden/octopusdeploy-worker-tools](https://hub.docker.com/repository/docker/pvanderheijden/octopusdeploy-worker-tools)) and added it to my Octopus Deploy project. Works like a charm!

### CODE REVIEW

**Comment by pietervdheijden-calvi** [comment]
@Gwash3189 @emilol @MJRichardson @tothegills @mcasperson @matt-richardson @Justin-Walsh @wordlee @APErebus @andrewabest @mattboschatliveoak @geofflamrock @shaunmarx

Can someone please review this pull request? 😄

**Comment by andrewabest** [comment]
Sorry for the delay @pietervdheijden-calvi - thanks for the contribution, I'll take a look at it now!

**Review by andrewabest — APPROVED** [review]
Looks good, I've reviewed the helm release notes, and it looks like the only breaking changes would be for anyone relying on experimental OCI features. Let's ship this, and I'll make a corresponding minor bump to the published artifacts.

**Comment by pietervdheijden-calvi** [comment]
@andrewabest Thanks! I've updated my Octopus Deploy projects to use the new Docker image (octopusdeploy/worker-tools:3.3.1-ubuntu.18.04).

Out of curiosity: how is your CI/CD pipeline triggered and how is the next version number determined?

**Comment by andrewabest** [comment]
> @andrewabest Thanks! I've updated my Octopus Deploy projects to use the new Docker image (octopusdeploy/worker-tools:3.3.1-ubuntu.18.04).
> 
> Out of curiosity: how is your CI/CD pipeline triggered and how is the next version number determined?

The pipeline will build on any commit to a branch, however the publish flow is triggered by tagging. The version number is derived from the tag. Given the nature of this repo, it is easiest for a human to decide which version number should come next, rather than trying to derive it from git history.

**Comment by pietervdheijden-calvi** [comment]
> The pipeline will build on any commit to a branch, however the publish flow is triggered by tagging. The version number is derived from the tag. Given the nature of this repo, it is easiest for a human to decide which version number should come next, rather than trying to derive it from git history.

Thanks!

And how does the publish flow link tags to the build output (e.g. binaries, images, etc.)? Does it use Git SHAs?

**Pull request merged**
