### PR TITLE
Add Octopus CLI EAP to Worker Tools

### PR DESCRIPTION
**Pull request by benjimac93**

### CODE REVIEW

**Comment by benjimac93** [comment]
@hnrkndrssn Lets see if this one works :)

**Review by hnrkndrssn — APPROVED** [review]

**Comment by hnrkndrssn** [comment]
Hey @benjimac93 I've been investigating why your PR is not kicking off the required builds and have found that our builds are only configured to run if the author is a member of the `OctopusDeploy` organization.

I'm not quite sure why this is so I will take this to our builds team to see if there is a specific reason for this. In the meantime, I'll grab your changes and push up a new PR so we can get your changes merged.

Once again, I sincerely apologies for these blockers and run around.

**Comment by benjimac93** [comment]
Thanks @hnrkndrssn ! Have a fantastic weekend

**Comment by hnrkndrssn** [comment]
> Thanks @hnrkndrssn ! Have a fantastic weekend

Thank you, have a great weekend!

**Comment by hnrkndrssn** [comment]
Hey @benjimac93 I've merged your changes as part of #80 so I will close this PR. Thank you for your contribution, it will make its way through our release pipeline now and become available in the near future.

**Pull request closed without merging**
