### PR TITLE
Added git and argocd to worker tools

### PR DESCRIPTION
**Pull request by mcasperson**
This PR adds `git` and `argocd` to the Windows worker image.

Also a few small updated to the Linux image to fix the tests and the package versions that are available now.

### CODE REVIEW

**Comment by APErebus** [comment]
@mcasperson  Any reason for windows only?

**Comment by mcasperson** [comment]
> @mcasperson Any reason for windows only?

Git is already on the Linux worker image.

**Comment by veochen-octopus** [comment]
Apologies about all the failed checks from the WIP project. That's a refactor of the build I'm working on. I've disabled the trigger for now.

**Comment by APErebus** [comment]
> > @mcasperson Any reason for windows only?
> 
> Git is already on the Linux worker image.

Is argocd?

**Pull request merged**
